In [2]:
from __future__ import print_function
import torch

In [6]:
x = torch.empty(5,3)
x

tensor([[ 1.4013e-45,  0.0000e+00,  1.1038e+09],
        [ 3.0726e-41,  3.9236e-44,  3.0726e-41],
        [-4.1692e-34,  4.5556e-41,  2.8026e-45],
        [ 4.5556e-41,  2.8026e-45,  4.5556e-41],
        [ 1.4013e-45,  0.0000e+00,  3.9236e-44]])

In [8]:
x = torch.rand(5,3)
x

tensor([[0.5097, 0.9023, 0.4587],
        [0.6211, 0.6862, 0.7468],
        [0.1053, 0.2811, 0.7790],
        [0.3416, 0.4746, 0.4132],
        [0.6439, 0.8560, 0.5679]])

In [10]:
x = torch.zeros(5,3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [12]:
x = torch.tensor([5,3])
x

tensor([5, 3])

In [14]:
x = x.new_zeros(5, 3, dtype=torch.float)
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [19]:
x = torch.randn_like(x, dtype = torch.float)
x

tensor([[-0.6722, -1.8374, -0.5144],
        [ 0.7700,  1.7508,  1.7163],
        [ 0.1156,  0.1888,  0.1573],
        [-0.1116,  0.3522, -0.6054],
        [-0.0820, -0.8400,  0.1028]])

In [20]:
x.size()

torch.Size([5, 3])

Anything method of the form <i>this_</i> modifies object in place

In [49]:
y = torch.zeros(5, 3)
y.add_(x)
y

tensor([[0.2777, 0.2777, 0.2777],
        [0.2777, 0.2777, 0.2777],
        [0.2777, 0.2777, 0.2777],
        [0.2777, 0.2777, 0.2777],
        [0.2777, 0.2777, 0.2777]])

In [54]:
c = torch.zeros(5,3)
d = torch.rand(5,3)
torch.add(y, d, out = c)
print(y+d)
print(c)

tensor([[0.8077, 0.4046, 0.5321],
        [0.6073, 0.8297, 0.3704],
        [1.0124, 0.4462, 0.4619],
        [0.7072, 1.0879, 0.8438],
        [1.1587, 0.9734, 0.7960]])
tensor([[0.8077, 0.4046, 0.5321],
        [0.6073, 0.8297, 0.3704],
        [1.0124, 0.4462, 0.4619],
        [0.7072, 1.0879, 0.8438],
        [1.1587, 0.9734, 0.7960]])


## There is stuff here
<ul>
<li> view is used for resizing tensors 
<li> the -1 infers the dimension automatically 

In [28]:
x = torch.rand(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [29]:
x = torch.rand(1)
x1 = x.item()
print(x1)

0.2777354121208191


### Numpy Stuff

Share same underlying memory location 

In [40]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [41]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [42]:
a.add_(1)
a

tensor([2., 2., 2., 2., 2.])

In [43]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [45]:
import numpy as np 
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [46]:
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [47]:
np.add(a, 1, out = a)

array([2., 2., 2., 2., 2.])

In [48]:
b

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [10]:
a = torch.tensor([[1,2],[3,8],[5,6]])

In [12]:
torch.max(a, 0, keepdim = True)

torch.return_types.max(
values=tensor([[5, 8]]),
indices=tensor([[2, 1]]))

In [9]:
a

tensor([[1, 2],
        [3, 4],
        [5, 6]])