In [1]:
import torch

In [4]:
x = torch.zeros(2,2, requires_grad = True)

In [5]:
x

tensor([[0., 0.],
        [0., 0.]], requires_grad=True)

In [6]:
y = x+5
y

tensor([[5., 5.],
        [5., 5.]], grad_fn=<AddBackward0>)

In [9]:
z = y*y+3
print(z)
out = z.mean()
print(out)

tensor([[28., 28.],
        [28., 28.]], grad_fn=<AddBackward0>)
tensor(28., grad_fn=<MeanBackward0>)


In [10]:
out.backward()

In [15]:
x.grad

tensor([[2.5000, 2.5000],
        [2.5000, 2.5000]])

The rest is beyond me 